version: '3.1'

services:
    mysql:
        image: mysql
        container_name: bd-mysql
        environment:
            MYSQL_USER: mysql
            MYSQL_PASSWORD: 123456
            MYSQL_DB: vemDBC
        ports:
            - "5432:5432"
        volumes:
            - data_mysql:/var/lib/mysql/data
volumes:
    data_mysql:
